### ISSUE TITLE
Fix launcher

### ISSUE THREAD

**Issue by oesteban** [poldracklab/crn-app-registration-tool#3]
```
Traceback (most recent call last):
  File "/corral-repl/utexas/poldracklab/users/wtriplet/external/ls5_launch/launch", line 57, in <module>
    use_hyperthreading=args.use_hyperthreading)
  File "/gpfs/corral3/repl/utexas/poldracklab/users/wtriplet/external/ls5_launch/launch_slurm_ls5.py", line 82, in launch_slurm_ls5
    print('Outputting qsub commands to %s' % qsubfilepath)
UnboundLocalError: local variable 'qsubfilepath' referenced before assignment
```

**Comment by oesteban** [comment]
We don't use our launcher script anymore. Closing
