### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/crn-app-registration-tool#9]
participant list was set to one participant

```
Traceback (most recent call last):
  File "/scratch/PI/russpold/crn-agave/anaconda/bin/cappwrapp", line 11, in <module>
    load_entry_point('cappat==0.0.3', 'console_scripts', 'cappwrapp')()
  File "/scratch/PI/russpold/crn-agave/anaconda/lib/python2.7/site-packages/cappat-0.0.3-py2.7.egg/cappat/wrapper.py", line 153, in main
    run_wrapper(parser.parse_args())
  File "/scratch/PI/russpold/crn-agave/anaconda/lib/python2.7/site-packages/cappat-0.0.3-py2.7.egg/cappat/wrapper.py", line 110, in run_wrapper
    randomize=app_settings.get('randomize_part_level', True))
  File "/scratch/PI/russpold/crn-agave/anaconda/lib/python2.7/site-packages/cappat-0.0.3-py2.7.egg/cappat/wrapper.py", line 41, in get_subject_list
    for subj in participant_label]
TypeError: 'int' object is not iterable
ERROR: cappwrap exit code was nonzero (1).
```

**Comment by oesteban** [comment]
This should be fixed now
